### ISSUE TITLE
Geometry branch

### ISSUE THREAD

**Issue by CapObvios** [DifanLiu/NeuralContours#3]
Hi! Thanks for the amazing research!

I'm interested in the extraction of the geometry-based maps. Could you please publish the code to extract, e.g., apparent ridges, ridges and valleys, and others?

**Comment by DifanLiu** [comment]
Hi! Thanks for your interest. 
We used the original rtsc-1.6 (https://gfx.cs.princeton.edu/proj/sugcon/) to extract all the feature maps and lines.

**Comment by CapObvios** [comment]
Thanks a lot!

Could you please also explain how did you automate the line extraction and how did you fit the camera views in rtsc?

**Comment by DifanLiu** [comment]
rtsc uses OpenGL to render line drawings. We turned off the GUI and modify the camera parameters of OpenGL context directly by calling commands such as gluPerspective and glulookat.

**Comment by Clement-Lelievre** [comment]
hi @DifanLiu 

I am trying to get the depth*.png and depth.png.
I have successfully compiled rtsc and made the modification to rtsc.cc that you mention [here](https://github.com/DifanLiu/NeuralContours/tree/master/data#view-based-shape-representations) but I still do not get the images as they are in the example data.

Could you please describe the steps to get them?

thanks
