### ISSUE TITLE
I'd like to see some images

### ISSUE THREAD

**Issue by andybak** [DifanLiu/NeuralContours#5]
The readme could either contain embedded images - or a link to the paper (which I presume contains images?)

(Answer - yes it does but I had to use google to find the paper: https://arxiv.org/pdf/2003.10333.pdf )

I can't be the only person that wants to see something visual when I find the repo for a project such as this.

**Comment by DifanLiu** [comment]
Thanks for the suggestion. I just put a link to the paper in README.
