### ISSUE TITLE
code license?

### ISSUE THREAD

**Issue by v-a-s-a** [DifanLiu/NeuralContours#6]
Very cool work! Any thoughts on adding a code license here?

**Comment by DifanLiu** [comment]
Hi, thanks for your interest! Currently a license is not in our plan. Feel free to use it for non-commercial purpose. 
For commercial purpose, please contact dliu@cs.umass.edu.

**Comment by v-a-s-a** [comment]
I have no commercial interests here, just an increasing awareness of how I interact with open/closed software.

In this case, I would encourage you to add a copyright statement. Unlicensed code is by [default unusable by others](https://choosealicense.com/no-permission/), but it still serves as an important record for your published work.
