### ISSUE TITLE
Could you share rtsc-1.6 file?

### ISSUE THREAD

**Issue by JihwanEom** [DifanLiu/NeuralContours#7]
Hello, thank you for your awesome works!

I want to use NeuralContours on my custom dataset, but they need precomputed geometric features.

I've tried several times for editing and compiling rtsc-1.6, however it was so hard from lack of informations.

Could you share modified rtsc-1.6 files?

Thank you!

**Comment by DifanLiu** [comment]
Replied in the email thread.

**Comment by YufengLii** [comment]
Thanks for your great work on NPR.
In my work, we want to be able to use RTSC to use a given view point and 3D model to generate annotation data, but the original RTSC code does not contain the input of the camera's perspective and the output of the image, if you can share your modified RTSC code, which I believe will be easier with your foundation.

Thanks again and best wishes.

**Comment by ty625911724** [comment]
Dear authors:

Thanks a lot for your great works! I also want to use NeuralContours on my own dataset. Could you share modified rtsc-1.6 files?

Thank you!

**Comment by Clement-Lelievre** [comment]
hello

same here.
I need the depth*.png files, and despite making the modifications you mention in https://github.com/DifanLiu/NeuralContours/tree/master/data#view-based-shape-representations , I cannot get them.

could you please share your rtsc1.6 modified files?

thank you
